prysmex/ember-eui

addon/helpers/arg-or-default.ts
addon/helpers/class-names.ts
addon/helpers/unique-id.ts

Important changes required for the other PRs

Augment helpers

---

addon/components/eui-accordion/index.hbs
addon/components/eui-accordion/index.ts
addon/utils/css-mappings/eui-accordion.ts
addon/utils/css-mappings/index.ts
app/components/eui-accordion/index.js
tests/dummy/app/templates/application.hbs

EuiAccordion Fix PR

---

CHANGELOG.md
README.md
addon/components/eui-icon/index.hbs
addon/components/eui-icon/index.ts
package.json

Add empty icon while loading the svg

Add empty icon while loading the svg

---

addon/components/eui-flex-group/index.hbs

Flex Group Update

---

addon/components/eui-callout/index.hbs
addon/components/eui-flex-grid/index.hbs
addon/components/eui-flex-item/index.hbs
addon/components/eui-page-body/index.hbs
addon/components/eui-text-color/index.hbs
addon/components/eui-text/index.hbs
addon/components/eui-title/index.hbs
addon/components/text/index.hbs
app/components/text/index.js
tests/dummy/app/templates/demo/text.hbs
yarn.lock

fallback to static dom instead of element helper for performance gains

fallback to static dom instead of element helper for performance gains

---

addon/components/eui-horizontal-rule/index.hbs
addon/helpers/class-names.ts
addon/utils/css-mappings/eui-horizontal-rule.ts
addon/utils/css-mappings/index.ts
app/components/eui-horizontal-rule/index.js
tests/dummy/app/controllers/application.js
tests/dummy/app/router.js
tests/dummy/app/routes/demo/horizontal-rule.ts
tests/dummy/app/templates/demo/horizontal-rule.hbs

Eui Horinzontal Rule
closes #37

Eui Horizontal Rule

---

addon/components/eui-image/index.hbs
addon/components/eui-overlay-mask/index.hbs
tests/dummy/app/templates/demo/image.hbs

Fix icon position when image is fullscreen.

fix image close icon

---

packages/core/addon/components/eui-card/index.hbs

Adding title named block to eui-card file for better handling.

Add named block title to card

---

packages/core/addon/components/eui-card/index.hbs

dz_somefixes 

---

packages/changeset-form/addon/components/eui-changeset-form/fields/field-checkbox-group/index.hbs
packages/changeset-form/addon/components/eui-changeset-form/fields/field-dual-range-slider/index.hbs
packages/changeset-form/addon/components/eui-changeset-form/fields/field-number/index.hbs
packages/changeset-form/addon/components/eui-changeset-form/fields/field-password/index.hbs
packages/changeset-form/addon/components/eui-changeset-form/fields/field-radio-group/index.hbs
packages/changeset-form/addon/components/eui-changeset-form/fields/field-range-slider/index.hbs
packages/changeset-form/addon/components/eui-changeset-form/fields/field-select/index.hbs
packages/changeset-form/addon/components/eui-changeset-form/fields/field-text-area/index.hbs
packages/changeset-form/addon/components/eui-changeset-form/fields/field-text/index.hbs

add rowClasses and splat attributes con input component

dz_PA-euiChangesetFormInputs

---

packages/core/addon/components/eui-tabbed-content/index.hbs

Pass tab.disable for disabling tabs

feat: pass disabled con tab

---

packages/core/docs/display/tool-tip-demo/demo1.md
packages/core/docs/display/tool-tip-demo/demo2.md
packages/core/docs/display/tool-tip-demo/demo3.md
packages/core/docs/display/tool-tip.md

euitooltip-docs

---

packages/core/docs/display/title-demo/demo1.md

EuiTitle docs

---

packages/core/docs/display/text-demo/demo1.md
packages/core/docs/display/text-demo/demo2.md
packages/core/docs/display/text-demo/demo3.md
packages/core/docs/display/text.md

eui-text-docs

---

packages/core/docs/display/health-demo/demo1.md
packages/core/docs/display/health-demo/demo2.md
packages/core/docs/display/health.md

health docs

---

packages/core/docs/display/callout-demo/demo1.md
packages/core/docs/display/callout-demo/demo2.md
packages/core/docs/display/callout-demo/demo3.md
packages/core/docs/display/callout-demo/demo4.md
packages/core/docs/display/callout.md

docs Eui-callout

---

packages/core/docs/display/progress-demo/demo1.md
packages/core/docs/display/progress-demo/demo2.md
packages/core/docs/display/progress-demo/demo3.md
packages/core/docs/display/progress-demo/demo4.md

Euiprogress-docs

---

packages/core/docs/display/badge-demo/demo1.md
packages/core/docs/display/badge-demo/demo2.md
packages/core/docs/display/badge-demo/demo3.md
packages/core/docs/display/badge-demo/demo4.md
packages/core/docs/display/badge-demo/demo5.md
packages/core/docs/display/badge-demo/demo6.md
packages/core/docs/display/badge-demo/demo7.md
packages/core/docs/display/badge-demo/demo8.md

badge docs

---

packages/core/docs/navigation/tabs-demo/demo1.md
packages/core/docs/navigation/tabs-demo/demo2.md
packages/core/docs/navigation/tabs-demo/demo3.md
packages/core/docs/navigation/tabs-demo/demo4.md

Eui-Tabs docs

---

packages/flatpickr/addon/components/eui-flatpickr/index.hbs
packages/flatpickr/addon/components/eui-flatpickr/index.js
packages/flatpickr/docs/flatpickr-demo/demo1.md

add eui form control layour on flatpicker

Feat: add eui form control layour on flatpicker

---

packages/core/addon/components/eui-markdown-format/index.hbs
packages/core/addon/components/eui-markdown-format/index.ts
packages/core/addon/utils/markdown/plugins/to-dom.ts

Fixes markdown format plugins to render components

fix: markdown format

---

packages/core/src/components/eui-badge.gts
packages/core/src/components/eui-stat.gts
packages/core/src/components/eui-super-date-picker.gts
packages/core/src/components/eui-tool-tip.gts

1. Fix color argument type in EuiBadge
2. Make optional some arguments of EuiStat, screenReader isn't used yet
3. Reexport some EuiSuperDatePicker types
4. @classname arg in EuiToolTip wasn't being used

General minor fixes
